### PR TITLE
FIX rel attribute in external links

### PR DESCRIPTION
**Pull request by jormee**
Hi Tejas,
The relevant changes to the `rel` attribute of the links have been made

### CODE REVIEW

**Review by TejasQ — COMMENTED** [review]
Why did `yarn.lock` change?

**Comment by jormee** [comment]
Hi Tejas,

Had issues installing the dependencies for the app, so I had to delete the yarn.lock and  run `yarn install` again which installed the latest version of all dependencies in the file.

If you could check through the changes in the yarn.lock file, you'd realise they are only changes to the version of the dependencies.

**Review by TejasQ — APPROVED** [review]

**Comment by TejasQ** [comment]
Thanks for your contribution!

**Comment by jormee** [comment]
Anytime man, I love you

**Pull request merged**
